SELECT * FROM customer_behavior.customer;
SELECT COUNT(*) FROM customer;

-- Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) 
from customer
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount
from customer
where purchase_amount >= (select avg(purchase_amount) from customer) and discount_applied = 'Yes';


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5;
  
  
--  Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, (AVG(purchase_amount)) 
from customer 
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q 5  Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers. 